# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admincenter_files', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='nom_modul_nota',
            new_name='id_modul_nota',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='uf_nota',
            new_name='id_uf_nota',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='dni_usuari_nota',
            new_name='id_usuari_nota',
        ),
        migrations.RenameField(
            model_name='uf',
            old_name='nom_modul_nota',
            new_name='id_modul_nota',
        ),
    ]
