# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admincenter_files', '0002_auto_20170504_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modul',
            old_name='nom_modul',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='id_modul_nota',
            new_name='modul',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='nota_nota',
            new_name='nota',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='id_uf_nota',
            new_name='uf',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='id_usuari_nota',
            new_name='usuari',
        ),
        migrations.RenameField(
            model_name='uf',
            old_name='id_modul_nota',
            new_name='modul',
        ),
        migrations.RenameField(
            model_name='uf',
            old_name='nom_uf',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='usuari',
            old_name='dni_usuari',
            new_name='dni',
        ),
        migrations.RenameField(
            model_name='usuari',
            old_name='password_usuari',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='usuari',
            old_name='username_usuari',
            new_name='username',
        ),
    ]
