# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admincenter_files', '0005_alumne'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumne',
        ),
    ]
