# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admincenter_files', '0011_auto_20170510_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='professor',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
