# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admincenter_files', '0013_auto_20170510_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admincenter_files.Professor'),
        ),
        migrations.AddField(
            model_name='alumne',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admincenter_files.Classe'),
        ),
    ]
