# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admincenter_files', '0015_auto_20170510_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='modul',
            name='classe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admincenter_files.Classe'),
            preserve_default=False,
        ),
    ]
