# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincenter_files', '0018_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumne',
            name='cognoms',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
