# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincenter_files', '0019_alumne_cognoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='horari',
            name='id_profesor_xml',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horari',
            name='nomprofes',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
