# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-12 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincenter_files', '0020_auto_20170511_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='dni',
            new_name='departament_professor',
        ),
        migrations.RemoveField(
            model_name='horari',
            name='id_profesor_xml',
        ),
        migrations.AddField(
            model_name='professor',
            name='professor_id_xml',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='text',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
