# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincenter_files', '0024_classe_id_xml'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_xml', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
    ]
