# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admincenter_files', '0026_classe_class_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='class_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admincenter_files.Room'),
        ),
    ]
