# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincenter_files', '0027_auto_20170515_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='class_room',
            field=models.CharField(max_length=200),
        ),
    ]
