# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincenter_files', '0028_auto_20170515_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_xml', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('forecolor', models.CharField(max_length=200)),
                ('backcolor', models.CharField(max_length=200)),
            ],
        ),
    ]
