# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincenter_files', '0029_assignatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='llico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_xml', models.CharField(max_length=200)),
                ('periods', models.CharField(max_length=200)),
                ('lesson_subject', models.CharField(max_length=200)),
                ('lesson_teacher', models.CharField(max_length=200)),
                ('effectivebegindate', models.CharField(max_length=200)),
                ('effectiveenddate', models.CharField(max_length=200)),
                ('assigned_day', models.CharField(max_length=200)),
                ('assigned_period', models.CharField(max_length=200)),
                ('assigned_starttime', models.CharField(max_length=200)),
                ('assigned_endtime', models.CharField(max_length=200)),
            ],
        ),
    ]
