# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincenter_files', '0030_llico'),
    ]

    operations = [
        migrations.AddField(
            model_name='llico',
            name='teacher_value',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
