# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincenter_files', '0031_llico_teacher_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horari',
            old_name='hora',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='horari',
            old_name='classe',
            new_name='endtime',
        ),
        migrations.RenameField(
            model_name='horari',
            old_name='nomprofes',
            new_name='id_xml',
        ),
        migrations.RenameField(
            model_name='horari',
            old_name='professor_id_xml',
            new_name='period',
        ),
        migrations.AddField(
            model_name='horari',
            name='starttime',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
