# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincenter_files', '0033_auto_20170515_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_alumne', models.CharField(max_length=200)),
                ('dia', models.CharField(max_length=200)),
                ('hora', models.CharField(max_length=200)),
                ('llico', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fitxatge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ldap', models.CharField(max_length=200)),
                ('origenlector', models.CharField(max_length=200)),
                ('dia_hora', models.CharField(max_length=200)),
                ('id_tarjeta', models.CharField(max_length=200)),
            ],
        ),
    ]
