# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincenter_files', '0034_assistencia_fitxatge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumne',
            old_name='cognoms',
            new_name='codi',
        ),
        migrations.RenameField(
            model_name='alumne',
            old_name='dni',
            new_name='etapa',
        ),
        migrations.RemoveField(
            model_name='alumne',
            name='classe',
        ),
        migrations.AddField(
            model_name='alumne',
            name='id_alumne',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumne',
            name='id_grup',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumne',
            name='nivell',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumne',
            name='regim',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumne',
            name='subetapa',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
