# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincenter_files', '0035_auto_20170516_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Llico_classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_llico', models.CharField(max_length=200)),
                ('id_classe', models.CharField(max_length=200)),
                ('room', models.CharField(max_length=200)),
            ],
        ),
    ]
