# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-18 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincenter_files', '0038_alumne_nomalumne'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistencia',
            name='professor',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
